print('Meu crachá de programador(a)')

nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
linguagem = input('Digite sua linguagem favorita: ')
emoji = input('Digite um emoji que te representa: ')

print()

print("---------------------------------")

print()

print('Crachá do Dev')

print()

print(f'Nome: {nome}')
print(f'Idade: {idade}')
print(f'Linguagem favorita: {linguagem}')
print(f'Emoji: {emoji}')

print()

print("---------------------------------")


